name       : perl-parse-recdescent
version    : 1.967015
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/J/JT/JTBRAUN/Parse-RecDescent-1.967015.tar.gz : 1943336a4cb54f1788a733f0827c0c55db4310d5eae15e542639c9dd85656e37
homepage   : https://metacpan.org/pod/Parse::RecDescent
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Recursive descent parser generator
description: |
    Parse::RecDescent incrementally generates top-down recursive-descent text parsers from simple yacc-like grammar specifications.
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
